### PR TITLE
Modernize CMake usage

### PR DESCRIPTION
**Pull request by drbenmorgan**
From the topics discussed on the mailing list, I'll propose a few updates to simplify things.

### CODE REVIEW

**Comment by drbenmorgan** [comment]
O.k., ready for review - will need testing as commit  49088ca relies on SNFrontEndElectronics having set `INTERFACE_INCLUDE_DIRECTORIES` on the `SNFrontEndElectronics::snfee` target. Let me know, what if any messages appear and I can fix.

**Comment by emchauve** [comment]
It looks we need ```include_directories(${SNFrontEndElectronics_INCLUDE_DIRS})```

**Comment by drbenmorgan** [comment]
O.k., fixed in the latest commit - the long term fix is already proposed to SNFrontEndElectronics: https://gitlab.in2p3.fr/SuperNEMO-DBD/SNFrontEndElectronics/-/merge_requests/2

**Comment by emchauve** [comment]
OK! compiling and running, I will merge then

**Pull request merged**
